targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
      flutter_gen:
        options:
          output: lib/app/gen/
          assets:
            exclude:
              - .env
          integrations:
            flutter_svg: true
          fonts:
            enabled: false
      slang_build_runner:
        options:
          base_locale: ru
