name: icebreaker_talk_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  theme_tailor_annotation: 3.1.0
  flutter_screenutil: 5.9.3
  retrofit: 4.7.1
  dio: 5.9.0
  injectable: 2.5.1
  get_it: 8.2.0
  flutter_dotenv: 6.0.0
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0
  flutter_bloc: ^9.1.1
  flutter_svg: 2.2.0
  talker_flutter: 5.0.0
  talker_dio_logger: 5.0.0
  slang: 4.8.1
  slang_flutter: 4.8.0
  go_router: 16.2.0
  flutter_card_swiper: 7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner: 2.6.0
  theme_tailor: 3.1.0
  injectable_generator: 2.8.1
  freezed: 3.2.0
  json_serializable: 6.10.0
  retrofit_generator: 10.0.2
  flutter_gen_runner: 5.11.0
  slang_build_runner: 4.8.0
  go_router_builder: 3.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/manrope/Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/ExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/ExtraBold.ttf
          weight: 800
